### ISSUE TITLE
Modify launcher page to better explain what launcher is and that it is not all you need.

### ISSUE THREAD

**Issue by carsonblack** [hechoendrupal/drupal-console-book#263]
The instructions here don't mention that launcher is not all you need to get console working for any given site: https://docs.drupalconsole.com/en/getting/launcher.html

Or at least, they don't explain what the launcher actually is. There's no mention that it's not the whole of Drupal Console.

**Comment by nvaken** [comment]
I think it's more of a problem of simply landing on that specific page. Since the [main chapter page](https://docs.drupalconsole.com/en/getting/project.html) actually does do a fine job explaining why you need the launcher. Still, it might be good to at least mention on that page that you need more then just the launcher and refer to the main chapter?

**Comment by jmolivas** [comment]
I think as well Closing this one. Feel free to re-open if page require more clarification.

Thanks for fixing the page during DrupalCon @carsonblack 

PR https://github.com/hechoendrupal/drupal-console-book/pull/257/files
